### PR TITLE
fix: set helper on window in testing

### LINKED ISSUE #335: Module crashes in Vitest with nuxt environment test suites
### Version
@nuxtjs/color-mode: v4.0.0
nuxt: v4.2.1

### Reproduction Link
- https://github.com/janhoogeveen/color-mode

Relevant files are:
- https://github.com/janhoogeveen/color-mode/blob/main/test/nuxt/app.nuxt.spec.ts
- https://github.com/janhoogeveen/color-mode/blob/main/src/runtime/plugin.client.ts

### Steps to reproduce

I've previously [submitted a patch](https://github.com/nuxt-modules/color-mode/pull/325) to address the access of unknown properties. It seems the patch as-merged does not work as intended.

The only way to reproduce this accordingly is to write a test suite that uses the Nuxt environment to run a test. E.g. write a test that renders the ColorModePicker component from the playground in a nuxt environment in Vitest.

This will trigger an error.

```
TypeError: Cannot read properties of undefined (reading 'preference')
 ❯ playground/components/ColorModePicker.vue:16:85
```

### What is Expected?

I expect the colorModule return values to always be defined. OR, be typed truthfully and indicate some values might be undefined.

### What is actually happening?
When running in Vitest nuxt environment, I suspect window is not defined and as such helper is not defined either. The current solution does not stub the module correctly.

I see multiple reasons:

1. The type declaration of the Helper is untruthful.

The following snippet tells TypeScript that helper will always be of type Helper. This is false. 

```ts
// eslint-disable-next-line @typescript-eslint/no-explicit-any
let helper = window[globalName as any] as unknown as Helper
```

2. Conditional stubbing not firing correctly
For some reason, the following snippet will not evaluate as truthy in a nuxt vitest environment. I think because it needs to be `import.meta.TEST`.

```ts
if (import.meta.test && !helper) {
```

### LINKED ISSUE #342: Run vitest crashes when module is installed on it's 4.0.0 version
### Version
@nuxtjs/color-mode: 4.0.0
nuxt: 4.2.1

### Reproduction Link

https://github.com/ThomasBerneHCSE/nuxt-i18n-on-test-reproduction

### Steps to reproduce

steps to reproduce : 

1. Instal deps
```
$ npm install
```

2. Run tests
```
$ npm run test
```

### What is Expected?

The tests should run fine. Remove the `@nuxtjs/color-mode` and everything works great. Roll back it's version to v3.X.X and everything works great.

### What is actually happening?
You will encounter an issue where $setup.t is not a function and other issues on things not defined during tests : 
image

### PR DESCRIPTION
**Pull request by danielroe**
### 🔗 Linked issue

resolves https://github.com/nuxt-modules/color-mode/issues/342
resolves #335

### ❓ Type of change

- [x] 🐞 Bug fix (a non-breaking change that fixes an issue)

### 📚 Description

previously we set helper but didn't make the helper available on the window object.

regression from https://github.com/nuxt-modules/color-mode/pull/325

### CODE REVIEW

**Comment by benjamincanac** [comment]
@danielroe any news on this?

**Review by atinux — APPROVED** [review]

**Comment by danielroe** [comment]
oh! i should have marked this draft as i'm not sure this solves the problem 🤦
